-- CreateTable
CREATE TABLE "Order" (
    "id" SERIAL NOT NULL,
    "order_id" INTEGER NOT NULL,
    "order_date" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "item_id" INTEGER NOT NULL,
    "sku" TEXT NOT NULL,
    "qty_ordered" INTEGER NOT NULL,
    "price" DECIMAL(65,30) NOT NULL,
    "value" DECIMAL(65,30) NOT NULL,
    "discount_amount" DOUBLE PRECISION NOT NULL,
    "total" DECIMAL(65,30) NOT NULL,
    "category" TEXT NOT NULL,
    "payment_method" TEXT NOT NULL,
    "bi_st" TEXT NOT NULL,
    "cust_id" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "month" TEXT NOT NULL,
    "ref_num" INTEGER NOT NULL,
    "customer_since" TEXT NOT NULL,
    "place_name" TEXT NOT NULL,
    "county" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zip" INTEGER NOT NULL,
    "region" TEXT NOT NULL,
    "discount_percent" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);
